### ISSUE TITLE
Can´t manage to create new client

### ISSUE THREAD

**Issue by martensson** [ansd/lastpass-go#27]
Hi!
I am very interested in using this library, but I am having trouble to start trying it out. I am using 2FA, but no matter how I try to login I always get the following error: `input is only 0 bytes; expected at least 16 bytes`. Not sure if it is because Lastpass changed something or what it could be. Using the following snippet:

```
	logger := log.New(os.Stderr, "client logger ", log.LstdFlags)
	client, err := lastpass.NewClient(context.Background(), "email", "hunter123", lastpass.WithOneTimePassword("123456"), lastpass.WithLogger(logger))
	if err != nil {
		log.Fatalln(err)
	}
```

Thanks a lot for this library!

**Comment by martensson** [comment]
Managed to solve this issue, needed to set the BaseURL to `https://lastpass.eu` being in Europe. 
Hope it can help other Europeans eventually.

**Comment by ansd** [comment]
Hey @martensson,

many thanks for letting us know to set the BaseURL to `https://lastpass.eu/` for European accounts.

Using method [WithBaseURL](https://pkg.go.dev/github.com/ansd/lastpass-go#WithBaseURL) is a good workaround 🙂
I originally added that method to set the base URL of the fake server when running unit tests.
Ideally, you and other users wouldn't need to use that method at all.
Instead this lastpass-go library could implement what was done in [this lastpass-cli commit](https://github.com/lastpass/lastpass-cli/commit/f423d46ae3b36feab33c51caaee8cb4dff536e50).
What do you think?
If you think that makes sense, I'd be happy to try adding support for `lastpass.eu`.

**Comment by martensson** [comment]
Hey again @ansd! This would be a fantastic feature to make the library detect the location. But I understand if it requires some extra work on your end. I believe we could live with setting the baseurl manually, but I am sure there might be other confused users out there who have no idea why it's failing ;)
