### ISSUE TITLE
Error while calling NewClient

### ISSUE THREAD

**Issue by kaplanelad** [ansd/lastpass-go#52]
Hey, 

I'm getting an error when trying to create `NewClient` function. see example:
```go
client, err := lastpass.NewClient(context.Background(), username, masterPassword)
```

The error is:
`input is only 0 bytes; expected at least 16 bytes`

It looks like the field `privatekeyenc` returns empty from API, and the function `decryptPrivateKey` based on this field returns an error.

**Comment by ansd** [comment]
Hey @kaplanelad,

Thanks for reporting this issue.

I could reproduce this issue by creating an account via https://lastpass.com/create-account.php and logging in with this Go library **without** previously logging in via the Chrome extension.
Logging in with the Chrome extension (and probably any other officially supported client) at least once will generate the sharing RSA key and from then on include the `privatekeyenc` in the HTTP response.

So, my 1st question is:
What is your workflow? Are my reproduction steps how you also ended up with this issue?
(I'm trying to understand whether there are any other cases where `privatekeyenc` won't be included for LastPass accounts even if they logged in previously via any officially supported client.)

I just pushed a commit to `master` branch which fixes this issue.
My 2nd question is:
Can you please try it out and confirm it fixes your use case?

Thanks!

**Comment by kaplanelad** [comment]
Thanks @ansd, it woks now

**Comment by ansd** [comment]
Thank you @kaplanelad for testing and confirming.
I cut https://github.com/ansd/lastpass-go/releases/tag/v0.3.2.
